//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.18 at 09:58:24 PM CET 
//

package com.pecunia.edek.common;

import java.util.HashMap;
import java.util.Map;

public class TAdresPolski extends TAdresBase {

	public TAdresPolski(String name, Map<String, String> data, String sufix) {
		super(name);
		namespace("etd", data);
		setKodKraju("PL", data);
		setWojewodztwo(data.get("Wojewodztwo" + sufix), data);
		setPowiat(data.get("Powiat" + sufix), data);
		setGmina(data.get("Gmina" + sufix), data);
		setUlica(data.get("Ulica" + sufix), data);
		setNrDomu(data.get("NrDomu" + sufix), data);
		setNrLokalu(data.get("NrLokalu" + sufix), data);
		setMiejscowosc(data.get("Miejscowosc" + sufix), data);
		setKodPocztowy(data.get("KodPocztowy" + sufix), data);
		setPoczta(data.get("Poczta" + sufix), data);
	}

	public TAdresPolski() {
		super("AdresPol");
		setKodKraju("PL", new HashMap<String, String>());
	}

	public TAdresPolski(Map<String, String> data, String sufix) {
		this("AdresPol", data, sufix);
	}

	public void setWojewodztwo(String value, Map<String, String> data) {
		setSub("Wojewodztwo", new TJednAdmin("Wojewodztwo", value, data));
	}

	public void setPowiat(String value, Map<String, String> data) {
		setSub("Powiat", new TJednAdmin("Powiat", value, data));
	}

	public void setGmina(String value, Map<String, String> data) {
		setSub("Gmina", new TJednAdmin("Gmina", value, data));
	}

	public void setPoczta(String value, Map<String, String> data) {
		setSub("Poczta", new TMiejscowosc("Poczta", value, data));
	}

}
