//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.18 at 09:58:24 PM CET 
//

package com.pecunia.edek.common;

import java.util.Map;

public abstract class TAdresBase extends Element {

	public TAdresBase(String name) {
		super(name);
	}

	public void setKodKraju(String value, Map<String, String> data) {
		setSub("KodKraju", new TKodKraju(value, data));
	}

	public void setKodPocztowy(String value, Map<String, String> data) {
		setSub("KodPocztowy", new TKodPocztowy(value, data));
	}

	public void setMiejscowosc(String value, Map<String, String> data) {
		setSub("Miejscowosc", new TMiejscowosc("Miejscowosc", value, data));
	}

	public void setUlica(String value, Map<String, String> data) {
		if (!exists(value)) {
			return;
		}
		setSub("Ulica", new TUlica(value, data));
	}

	public void setNrDomu(String value, Map<String, String> data) {
		setSub("NrDomu", new TNrBudynku("NrDomu", value, data));
	}

	public void setNrLokalu(String value, Map<String, String> data) {
		if (!exists(value)) {
			return;
		}
		setSub("NrLokalu", new TNrLokalu(value, data));
	}

}
