//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.18 at 09:58:24 PM CET 
//

package com.pecunia.edek.common;

import java.util.Map;

public class TIdentyfikatorOsobyFizycznej2 extends Element {

	// @XmlElement(name = "NIP", required = true)
	// protected String nip;
	// @XmlElement(name = "ImiePierwsze", required = true)
	// @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	// protected String imiePierwsze;
	// @XmlElement(name = "Nazwisko", required = true)
	// @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
	// protected String nazwisko;
	// @XmlElement(name = "DataUrodzenia", required = true)
	// protected XMLGregorianCalendar dataUrodzenia;
	// @XmlElement(name = "PESEL")
	// protected String pesel;

	public TIdentyfikatorOsobyFizycznej2() {
		super("OsobaFizyczna");
		// TODO Auto-generated constructor stub
	}

	public TIdentyfikatorOsobyFizycznej2(Map<String, String> data, String sufix) {
		this();
		namespace("etd", data);
		setNIP(data.get("NIP" + sufix), data);
		setImiePierwsze(data.get("Imie" + sufix), data);
		setNazwisko(data.get("Nazwisko" + sufix), data);
		setDataUrodzenia(parseDate(data.get("DataUrodzenia" + sufix)), data);
	}

	public void setNIP(String value, Map<String, String> data) {
		setSub("NIP", new TNrNIP(value, data));
	}

	public void setImiePierwsze(String value, Map<String, String> data) {
		setSub("Imie", new TImie("ImiePierwsze", value, data));
	}

	public void setNazwisko(String value, Map<String, String> data) {
		setSub("Nazwisko", new TNazwisko(value, data));
	}

	public void setDataUrodzenia(String date, Map<String, String> data) {
		setSub("DataUrodzenia", new TDate("DataUrodzenia", date, data));
	}


}
