//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.18 at 09:12:01 PM CET 
//


package com.pecunia.edek.common;



public enum TKodKrajuEnum {


    AF("AFGANISTAN","AF"),

    AX("ALAND ISLAND","AX"),

    AL("ALBANIA","AL"),

    DZ("ALGIERIA","DZ"),

    AD("ANDORA","AD"),

    AO("ANGOLA","AO"),

    AI("ANGUILLA","AI"),

    AQ("ANTARKTYDA","AQ"),

    AG("ANTIGUA I BARBUDA","AG"),

    AN("ANTYLE HOLENDERSKIE","AN"),

    SA("ARABIA SAUDYJSKA","SA"),

    AR("ARGENTYNA","AR"),

    AM("ARMENIA","AM"),

    AW("ARUBA","AW"),

    AU("AUSTRALIA","AU"),

    AT("AUSTRIA","AT"),

    AZ("AZERBEJDŻAN","AZ"),

    BS("BAHAMY","BS"),

    BH("BAHRAJN","BH"),

    BD("BANGLADESZ","BD"),

    BB("BARBADOS","BB"),

    BE("BELGIA","BE"),

    BZ("BELIZE","BZ"),

    BJ("BENIN","BJ"),

    BM("BERMUDY","BM"),

    BT("BHUTAN","BT"),

    BY("BIAŁORUŚ","BY"),

    BO("BOLIWIA","BO"),

    BA("BOŚNIA I HERCEGOWINA","BA"),

    BW("BOTSWANA","BW"),

    BR("BRAZYLIA","BR"),

    BN("BRUNEI DARUSSALAM","BN"),

    IO("BRYTYJSKIE TERYTORIUM OCEANU INDYJSKIEGO","IO"),

    BG("BUŁGARIA","BG"),

    BF("BURKINA FASO","BF"),

    BI("BURUNDI","BI"),

    CL("CHILE","CL"),

    CN("CHINY","CN"),

    HR("CHORWACJA","HR"),

    CY("CYPR","CY"),

    TD("CZAD","TD"),

    ME("CZARNOGÓRA","ME"),

    DK("DANIA","DK"),

    DM("DOMINIKA","DM"),

    DO("DOMINIKANA","DO"),

    DJ("DŻIBUTI","DJ"),

    EG("EGIPT","EG"),

    EC("EKWADOR","EC"),

    ER("ERYTREA","ER"),

    EE("ESTONIA","EE"),

    ET("ETIOPIA","ET"),

    FK("FALKLANDY","FK"),

    FJ("FIDŻI REPUBLIKA","FJ"),

    PH("FILIPINY","PH"),

    FI("FINLANDIA","FI"),

    FR("FRANCJA","FR"),

    TF("FRANCUSKIE TERYTORIUM PO�UDNIOWE","TF"),

    GA("GABON","GA"),

    GM("GAMBIA","GM"),

    GH("GHANA","GH"),

    GI("GIBRALTAR","GI"),

    GR("GRECJA","GR"),

    GD("GRENADA","GD"),

    GL("GRENLANDIA","GL"),

    GE("GRUZJA","GE"),

    GU("GUAM","GU"),

    GG("GUERNSEY","GG"),

    GY("GUJANA","GY"),

    GF("GUJANA FRANCUSKA","GF"),

    GP("GWADELUPA","GP"),

    GT("GWATEMALA","GT"),

    GN("GWINEA","GN"),

    GQ("GWINEA RÓWNIKOWA","GQ"),

    GW("GWINEA-BISSAU","GW"),

    HT("HAITI","HT"),

    ES("HISZPANIA","ES"),

    NL("HOLANDIA","NL"),

    HN("HONDURAS","HN"),

    HK("HONGKONG","HK"),

    IN("INDIE","IN"),

    ID("INDONEZJA","ID"),

    IQ("IRAK","IQ"),

    IR("IRAN","IR"),

    IE("IRLANDIA","IE"),

    IS("ISLANDIA","IS"),

    IL("IZRAEL","IL"),

    JM("JAMAJKA","JM"),

    JP("JAPONIA","JP"),

    YE("JEMEN","YE"),

    JE("JERSEY","JE"),

    JO("JORDANIA","JO"),

    KY("KAJMANY","KY"),

    KH("KAMBODŻA","KH"),

    CM("KAMERUN","CM"),

    CA("KANADA","CA"),

    QA("KATAR","QA"),

    KZ("KAZACHSTAN","KZ"),

    KE("KENIA","KE"),

    KG("KIRGISTAN","KG"),

    KI("KIRIBATI","KI"),

    CO("KOLUMBIA","CO"),

    KM("KOMORY","KM"),

    CG("KONGO","CG"),

    CD("KONGO, REPUBLIKA DEMOKRATYCZNA","CD"),

    KP("KOREAŃSKA REPUBLIKA LUDOWO-DEMOKRATYCZNA","KP"),

    XK("KOSOWO","XK"),

    CR("KOSTARYKA","CR"),

    CU("KUBA","CU"),

    KW("KUWEJT","KW"),

    LA("LAOS","LA"),

    LS("LESOTHO","LS"),

    LB("LIBAN","LB"),

    LR("LIBERIA","LR"),

    LY("LIBIA","LY"),

    LI("LIECHTENSTEIN","LI"),

    LT("LITWA","LT"),

    LV("ŁOTWA","LV"),

    LU("LUKSEMBURG","LU"),

    MK("MACEDONIA","MK"),

    MG("MADAGASKAR","MG"),

    YT("MAJOTTA","YT"),

    MO("MAKAO","MO"),

    MW("MALAWI","MW"),

    MV("MALEDIWY","MV"),

    MY("MALEZJA","MY"),

    ML("MALI","ML"),

    MT("MALTA","MT"),

    MP("MARIANY PÓŁNOCNE","MP"),

    MA("MAROKO","MA"),

    MQ("MARTYNIKA","MQ"),

    MR("MAURETANIA","MR"),

    MU("MAURITIUS","MU"),

    MX("MEKSYK","MX"),

    XL("MELILLA","XL"),

    FM("MIKRONEZJA","FM"),

    UM("MINOR","UM"),

    MD("MOŁDOWA","MD"),

    MC("MONAKO","MC"),

    MN("MONGOLIA","MN"),

    MS("MONTSERRAT","MS"),

    MZ("MOZAMBIK","MZ"),

    MM("MYANMAR (BURMA)","MM"),

    NA("NAMIBIA","NA"),

    NR("NAURU","NR"),

    NP("NEPAL","NP"),

    DE("NIEMCY","DE"),

    NE("NIGER","NE"),

    NG("NIGERIA","NG"),

    NI("NIKARAGUA","NI"),

    NU("NIUE","NU"),

    NF("NORFOLK","NF"),

    NO("NORWEGIA","NO"),

    NC("NOWA KALEDONIA","NC"),

    NZ("NOWA ZELANDIA","NZ"),

    PS("OKUPOWANE TERYTORIUM PALESTYNY","PS"),

    OM("OMAN","OM"),

    PK("PAKISTAN","PK"),

    PW("PALAU","PW"),

    PA("PANAMA","PA"),

    PG("PAPUA NOWA GWINEA","PG"),

    PY("PARAGWAJ","PY"),

    PE("PERU","PE"),

    PN("PITCAIRN","PN"),

    PF("POLINEZJA FRANCUSKA","PF"),

    PL("POLSKA","PL"),

    GS("POŁUDNIOWA GEORGIA I POŁUD.WYSPY SANDWICH","GS"),

    PT("PORTUGALIA","PT"),

    PR("PUERTO RICO","PR"),

    CF("REP.ŚRODKOWOAFRYKA�SKA","CF"),

    CZ("REPUBLIKA CZESKA","CZ"),

    KR("REPUBLIKA KOREI","KR"),

    ZA("REPUBLIKA POŁUDNIOWEJ AFRYKI","ZA"),

    RE("REUNION","RE"),

    RU("ROSJA","RU"),

    RO("RUMUNIA","RO"),

    RW("RWANDA","RW"),

    EH("SAHARA ZACHODNIA","EH"),

    BL("SAINT BARTHELEMY","BL"),

    KN("SAINT KITTS I NEVIS","KN"),

    LC("SAINT LUCIA","LC"),

    MF("SAINT MARTIN","MF"),

    VC("SAINT VINCENT I GRENADYNY","VC"),

    SV("SALWADOR","SV"),

    WS("SAMOA","WS"),

    AS("SAMOA AMERYKAŃSKIE","AS"),

    SM("SAN MARINO","SM"),

    SN("SENEGAL","SN"),

    RS("SERBIA","RS"),

    SC("SESZELE","SC"),

    SL("SIERRA LEONE","SL"),

    SG("SINGAPUR","SG"),

    SK("SŁOWACJA","SK"),

    SI("SŁOWENIA","SI"),

    SO("SOMALIA","SO"),

    LK("SRI LANKA","LK"),

    PM("ST. PIERRE I MIQUELON","PM"),

    US("STANY ZJEDNOCZONE AMERYKI","US"),

    SZ("SUAZI","SZ"),

    SD("SUDAN","SD"),

    SR("SURINAM","SR"),

    SJ("SVALBARD I JAN MAYEN","SJ"),

    SH("ŚWIĘTA HELENA","SH"),

    SY("SYRIA","SY"),

    CH("SZWAJCARIA","CH"),

    SE("SZWECJA","SE"),

    TJ("TADŻYKISTAN","TJ"),

    TH("TAJLANDIA","TH"),

    TW("TAJWAN","TW"),

    TZ("TANZANIA","TZ"),

    TG("TOGO","TG"),

    TK("TOKELAU","TK"),

    TO("TONGA","TO"),

    TT("TRYNIDAD I TOBAGO","TT"),

    TN("TUNEZJA","TN"),

    TR("TURCJA","TR"),

    TM("TURKMENISTAN","TM"),

    TV("TUVALU","TV"),

    UG("UGANDA","UG"),

    UA("UKRAINA","UA"),

    UY("URUGWAJ","UY"),

    UZ("UZBEKISTAN","UZ"),

    VU("VANUATU","VU"),

    WF("WALLIS I FUTUNA","WF"),

    VA("WATYKAN","VA"),

    HU("WĘGRY","HU"),

    VE("WENEZUELA","VE"),

    GB("WIELKA BRYTANIA","GB"),

    VN("WIETNAM","VN"),

    IT("WŁOCHY","IT"),

    TL("WSCHODNI TIMOR","TL"),

    CI("WYBRZEŻE KOŚCI SŁONIOWEJ","CI"),

    BV("WYSPA BOUVETA","BV"),

    CX("WYSPA BOŻEGO NARODZENIA","CX"),

    IM("WYSPA MAN","IM"),

    CK("WYSPY COOKA","CK"),

    VI("WYSPY DZIEWICZE-USA","VI"),

    VG("WYSPY DZIEWICZE-W.B.","VG"),

    HM("WYSPY HEARD I MCDONALD","HM"),

    CC("WYSPY KOKOSOWE (KEELINGA)","CC"),

    MH("WYSPY MARSHALLA","MH"),

    FO("WYSPY OWCZE","FO"),

    SB("WYSPY SALOMONA","SB"),

    ST("WYSPY ŚWIĘTEGO TOMASZA I KSIĄŻĘCA","ST"),

    TC("WYSPY TURKS I CAICOS","TC"),

    ZM("ZAMBIA","ZM"),

    CV("ZIELONY PRZYLĄDEK","CV"),

    ZW("ZIMBABWE","ZW"),

    AE("ZJEDNOCZONE EMIRATY ARABSKIE","AE");

    String fullName;
    String shortName;
    
    
    
    private TKodKrajuEnum(String fullName, String shortName) {
		this.fullName = fullName;
		this.shortName = shortName;
	}

    
	public String value() {
        return name();
    }

    public static TKodKrajuEnum fromValue(String v) {
		String upperCase = v.toUpperCase();
    	for (TKodKrajuEnum kod : values()) {
			if (upperCase.equals(kod.fullName) ||upperCase.equals(kod.shortName)) {
				return kod;
			}
    	}
    	return null;
    }

}

