//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.18 at 09:58:24 PM CET 
//

package com.pecunia.edek.common;

import java.util.Map;

public class TPodmiotDowolnyProsty extends Element {

	public TPodmiotDowolnyProsty() {
		super();
	}

	public TPodmiotDowolnyProsty(Map<String, String> data, String sufix, boolean etd) {
		super();
		String of = data.get("RodzajPodatnika");
		if ("1".equals(of)) {
			setOsobaNiefizyczna(new TIdentyfikatorOsobyNiefizycznejBezRegonu(data, false));
		} else {
			setOsobaFizyczna(new TIdentyfikatorOsobyFizycznejProsty(data, sufix, etd, false));
		}
	}

	public void setOsobaFizyczna(TIdentyfikatorOsobyFizycznejProsty value) {
		setSub("Osoba", value);
	}

	public void setOsobaNiefizyczna(TIdentyfikatorOsobyNiefizycznejBezRegonu value) {
		setSub("Osoba", value);
	}

}
