//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.02.18 at 09:58:24 PM CET 
//

package com.pecunia.edek.common;

import java.util.Map;

public class TPodmiotDowolnyBezAdresu3 extends Element {

	public TPodmiotDowolnyBezAdresu3() {
		super();
	}

	public TPodmiotDowolnyBezAdresu3(Map<String, String> data, String sufix) {
		super();
		String of = data.get("RodzajPodatnika");
		if ("1".equals(of)) {
			setOsobaNiefizyczna(new TIdentyfikatorOsobyNiefizycznej(data, false));
		} else {
			setOsobaFizyczna(new TIdentyfikatorOsobyFizycznej3(data, sufix));
		}
	}

	public TPodmiotDowolnyBezAdresu3(Map<String, String> data, String sufix, boolean etd) {
		super();
		String of = data.get("RodzajPodatnika");
		if ("1".equals(of)) {
			setOsobaNiefizyczna(new TIdentyfikatorOsobyNiefizycznej(data, etd));
		} else {
			setOsobaFizyczna(new TIdentyfikatorOsobyFizycznej3(data, sufix));
		}
	}

	public TPodmiotDowolnyBezAdresu3(Map<String, String> data, String sufix, boolean etd, boolean outeretd) {
		super();
		String of = data.get("RodzajPodatnika");
		if ("1".equals(of)) {
			setOsobaNiefizyczna(new TIdentyfikatorOsobyNiefizycznej(data, etd, outeretd));
		} else {
			setOsobaFizyczna(new TIdentyfikatorOsobyFizycznej3(data, sufix, etd, outeretd));
		}
	}

	public TPodmiotDowolnyBezAdresu3(Map<String, String> data) {
		super();
		String of = data.get("RodzajPodatnika");
		if ("1".equals(of)) {
			setOsobaNiefizyczna(new TIdentyfikatorOsobyNiefizycznej(data, true, false));
		} else {
			setOsobaFizyczna(new TIdentyfikatorOsobyFizycznej3(data, ""));
		}
	}

	public void setOsobaFizyczna(Element value) {
		setSub("Osoba", value);
	}

	public void setOsobaNiefizyczna(Element value) {
		setSub("Osoba", value);
	}

}
